micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
    schema-generate: CREATE_DROP
    dialect: POSTGRES
---
omdb:
  base-url: http://www.omdbapi.com/
  # Create your own apikey here http://www.omdbapi.com/. It's free
  apikey: xxxxxxxxxxxx
