micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
    schema-generate: CREATE_DROP
    dialect: POSTGRES
